### ISSUE TITLE
BG color unknown

### ISSUE THREAD

**Issue by NTBBloodbath** [kdav5758/TrueZen.nvim#15]
Hi, I'm getting this error when doing `:TZAtaraxis` but it doesn't happens with `:TZMinimalist`

```
E5108: Error executing lua ...Zen.nvim/lua/true-zen/services/mode-ataraxis/service.lua:378: Vim(highlight):E420: BG color unknown
```

Also when the error happens, I have to press `:q` several times as it leaves some empty buffers :confused: 

Here I leave my config info, in case it's useful:

- Neovim version: `NVIM v0.5.0-dev+1280-gbb7d3790b`
- Colorscheme: [doom-one](https://github.com/romgrk/doom-one.vim) (also happens when using transparent bg)

**Comment by NTBBloodbath** [comment]
Just saw issue #12 so I'll close this :)

**Comment by kdav5758** [comment]
Hey! I never got to see this issue but anyways: Their is a FAQ about this that explains how to solve this issue, but basically all it says is that you should use either for these settings:

```lua
custome_bg = "",
disable_bg_configuration = false
```

Hope you are enjoying the plugin! Yesterday a bunch of updates, new features and bug fixes were merge to main too, so be sure to check those out as well ;)
