### ISSUE TITLE
Cterm highlights being set unnecessarily

### ISSUE THREAD

**Issue by akinsho** [kdav5758/TrueZen.nvim#17]
@kdav5758 I was looking through the code a little and trying to understand the reason for the `E420` error, which you have a few settings to fix and it seems to be that whilst trying to hide the statusline this plugin specifically sets `ctermbg=bg` etc. https://github.com/kdav5758/TrueZen.nvim/blob/241a447913be439c1351ab0eadf805c4872622fc/lua/true-zen/services/mode-ataraxis/service.lua#L378

A lot of modern colour schemes only set `gui` values like `guifg` etc and no `cterm` values because really most modern editors can handle gui colors. A few lines below you seem to be checking a variable called `gui` and setting gui values only if `termguicolors` etc. is true. It seems to me you can do a similar check before trying to set `cterm` values

e.g.

```lua
if termguicolors then
 vim.cmd [[highlight Statusline guifg=fg guibg=bg]]
else
 vim.cmd [[highlight Statusline ctermfg=fg ctermbg=bg]]
end
```

Since if `termguicolors` is true then `cterm` is irrelevant so there's no point setting cterm values so it doesn't matter if a user has them or not

**Comment by kdav5758** [comment]
I have been developing some new stuff related to the hi groups ver recently on the `dev-mode-ataraxis-issue-10` branch (please excuse the mess in the code).

I'll look deeper into this tomorrow, as of now, this part that interacted with the hi groups was also """ready""", and (if I remember well) what I did was simply store the user's hi groups before fully entering `Ataraxis` mode and then resotering them when one exists it.

Thus, the `cterm` terms of every hi group will only be resotered if they were previously set by the user's settings.

Correct me if I'm wrong but wouldn't this solve the 
issue you pointed out (unnecessary `cterm` setting)?

If it does, please don't close the issue until the feature is merged to `main`. As I said, although it's working,  it's *dirty* right now. Here are two screenshots of one of the tests I ran:


**Get every value and store them all**
![IMG_20210429_235053_392](https://user-images.githubusercontent.com/58336662/116649988-e6814080-a945-11eb-9b89-fe9bd76fc708.jpg)


**Prepare the `hi` commands**
![IMG_20210429_235051_260](https://user-images.githubusercontent.com/58336662/116649990-e719d700-a945-11eb-8abc-391ba0b96005.jpg)

**Comment by akinsho** [comment]
@kdav5758 that sounds cool and like it might resolve the `cterm` issue I raised here. I'll wait till that gets merged to test it before closing this 👍🏾

**Comment by kdav5758** [comment]
Hello again @akinsho! All the updates, bug fixes, features and everything else was merged to main yesterday! And yes, this includes the fix for this issue.

Cheers!

**Comment by akinsho** [comment]
Awesome thanks @kdav5758
