### ISSUE TITLE
Zoom window

### ISSUE THREAD

**Issue by timsofteng** [kdav5758/TrueZen.nvim#7]
Hey. Can it plugin zoom one of the opened splits as maximizer do?
https://github.com/szw/vim-maximizer

I would use maximizer but it have a lot of bugs especially with terminal window resizing

**Comment by kdav5758** [comment]
I'm sorry but I installed the plugin and nothing happened. Neither `:MaximizeToggle` not `:MaximizeToggle!` worked. Could please explain what this plugin is supposed to do and if possible, attach a .gif showing what it does?

Thanks!

**Comment by timsofteng** [comment]
@kdav5758 sure. It maximize current split

Take a look at the screencast:

https://user-images.githubusercontent.com/51912173/115760768-3f7f3080-a3aa-11eb-9b01-a92f34493917.mp4

**Comment by kdav5758** [comment]
Done! Check the doc to see how to use it and configure it! Here: https://github.com/kdav5758/TrueZen.nvim#default

Basically it's just:
`:TZFocus`

**Comment by timsofteng** [comment]
Now it works as Maximizer. BUT. As I said before maximizer has some bugs or missed features.

Toggle :TZFocus and then try to resize whole your terminal window (gui window of alacritty, iterm2 or whatever). Then you will notice that layout will break espresially when you will try to unmaximize window back.

**Comment by kdav5758** [comment]
Hello again! No, unfortunately there is no way to control that. This a (Neo)Vim issue, not a TrueZen.nvim one. The only thing that makes `Focus` mode different from [Vim-Maximazer](https://github.com/szw/vim-maximizer) is that this one is smarter. Why? Because it does some maths to determine whether the window has already been focused by other means or not, Maximizer didn't do that!

**Comment by kdav5758** [comment]
After doing some research I found a way to accomplish this without breaking itself when changing the terminal's size.

Yesterday a bunch of updates, new features and bug fixes were merge to main too. One of those updates was the possibility to choose which focusing method to use.
![image](https://user-images.githubusercontent.com/58336662/116789733-eda76c00-aa75-11eb-8c60-0a523c89b9e5.png)

The `"experimental"` focusing method is the one you want! Please refer to the doc about this to learn what changed regarding the `Focus` mode and its config.

Hope you are enjoying the plugin!

**Comment by timsofteng** [comment]
@kdav5758 thanks! I'll try it later and share feedback.

**Comment by kdav5758** [comment]
Nice! let me know if you encountered any problems! and btw, there is also a demo .gif for this focusing method in the README :)

**Comment by timsofteng** [comment]
oh... Did I understand correctly? This "experimental window just open focused buffer in new tab, right? if so it's not what i need. I don't want to open new tab for my focused window. Tab is kind of workspace in my workflow. That's why I can't appreciate this solution.

**Comment by kdav5758** [comment]
> This "experimental" method just open focused buffer in new tab, right?

The `experiemental` focusing method creates a new tab displaying the current buffer (you could open several windows and run `:tabe %` to see it by yourself).

> if so it's not what i need. I don't want to open new tab for my focused window. Tab is kind of workspace in my workflow.

Hmm can I know how do you manage Tabs in your workflow?

> That's why I can't appreciate this solution.

Any ideas then?
